version: '3'
 
services:
  db:
    image: mysql:latest
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: app_db
      # MYSQL_USER: root
      MYSQL_PASSWORD: admin1234
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phphmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  dbdata:

# docker-compose -p mysql-phpmyadmin -f mysql-phpmyadmin-docker-compose.yml up -d